easy_admin:
    entities:
        Card:
            class: App\Entity\Card
        Categorie:
             class: App\Entity\Categorie
        Gegeven:
              class: App\Entity\Gegeven

        User:
          class: App\Entity\User

