# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    # configure resolvers
    resolvers:

        # setup the default resolver
        default:

            # use the default web path
            web_path: ~

    # your filter sets are defined here
    filter_sets:

        # use the default cache configuration
        cache: ~

        big:
            filters:
                thumbnail: {size: [900], mode: outbound, allow_upscale: true }


        medium:
            filters:
                thumbnail: {size: [600, 266], mode: outbound}

        small:
            filters:
                thumbnail: {size: [300], mode: outbound}