# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    # configure resolvers
    resolvers:

        # setup the default resolver
        default:

            # use the default web path
            web_path: ~

    # your filter sets are defined here
    filter_sets:

        # use the default cache configuration
        cache: ~

        big:
            filters:
                relative_resize:
                    heighten: 300
                    # Will allow smaller images to take 800px of height,
                    # width will change accordingly since aspect ration is still valid.
                    allow_upscale: true