# (or config/packages/stof_doctrine_extensions.yaml if you use Flex)
stof_doctrine_extensions:
  default_locale: nl
  orm:
    default:
      tree: true
      timestampable: false # not needed: listeners are not enabled by default
        timestampable: true
        sluggable: true
    other:
      timestampable: true

